#seek
RIGHT       no-osd seek +2
LEFT        no-osd seek -2
Shift+RIGHT no-osd seek  1 exact
Shift+LEFT  no-osd seek -1 exact

#Volume
UP          add volume  2
DOWN        add volume -2
MOUSE_BTN3  add volume  2
MOUSE_BTN4  add volume -2

#aspect ratio
A cycle-values video-aspect-override "16:9" "9:16" "4:3" "3:4" "13:16" "16:13" "2.35:1" "1:2.35" "11:20" "20:11" "-1"

#rotation
R cycle_values video-rotate "90" "180" "270" "0"

#brightness
b cycle_values brightness "0" "4"

# Time for uosc OSD
CTRL+t cycle-values script-opts uosc-time_precision=0 uosc-time_precision=3

#Chapters
N add chapter 1
MBTN_FORWARD add chapter 1
Alt+n add chapter -1
MBTN_BACK add chapter -1

#uosc
menu        script-binding uosc/menu
MBTN_MID    script-binding uosc/menu
# mbtn_right  script-binding uosc/menu
s           script-binding uosc/subtitles          #! الترجمة
a           script-binding uosc/audio              #! المسارات الصوتية
q           script-binding uosc/stream-quality     #! جودة البث
p           script-binding uosc/items              #! قائمة التشغيل
c           script-binding uosc/chapters           #! الفصول
ctrl+v      script-binding uosc/paste-to-open      #! لصق وفتح
ctrl+c      script-binding uosc/copy-to-clipboard  #! نسخ
ctrl+a      script-binding uosc/load-audio         #! تحميل ملف صوتي
h           script-binding memo-history            #! السجل
#           cycle ontop                            #! تثبيت في المقدمة
#           #! ---
#           set script-opts uosc-time_precision=0  #! دقة الوقت > افتراضي
#           set script-opts uosc-time_precision=4  #! دقة الوقت > ميلي ثانية
>           script-binding uosc/next               #! التالي
<           script-binding uosc/prev               #! السابق
alt+>       script-binding uosc/delete-file-next   #! حذف الملف والتالي
alt+<       script-binding uosc/delete-file-prev   #! حذف الملف والسابق
alt+esc     script-binding uosc/delete-file-quit   #! حذف الملف والخروج
o           script-binding uosc/open-file          #! فتح ملف
#           set video-aspect-override "-1"         #! نسبة العرض > افتراضي
#           set video-aspect-override "16:9"       #! نسبة العرض > 16:9
#           set video-aspect-override "4:3"        #! نسبة العرض > 4:3
#           set video-aspect-override "2.35:1"     #! نسبة العرض > 2.35:1
#           script-binding uosc/audio-device       #! أجهزة الصوت
#           script-binding uosc/editions           #! الإصدارات
ctrl+s      async screenshot                       #! لقطة شاشة
alt+i       script-binding uosc/keybinds           #! اختصارات لوحة المفاتيح
O           script-binding uosc/show-in-directory  #! عرض في المجلد
#           script-binding uosc/open-config-directory #! فتح مجلد الإعدادات
#           script-binding uosc/update             #! تحديث uosc
esc         quit #! خروج

